### ISSUE TITLE
Add Slovak lang

### ISSUE THREAD

**Issue by Nortonko** [Keksuccino/Linguji#7]
Hello,
thanks for your amazig works. Please can you add support for Slovak language?
Thanks.

**Comment by Keksuccino** [comment]
Hi! Uhm well yes, I can, but I don't know if Gemini and the other supported translation engines support it. But yeah, will add it in the next update if I don't forget it :)

**Comment by Nortonko** [comment]
Hi, thank you! The Gemini, DeepL and LibreTranslate support Slovak lang. So i think there will be no problem.

**Comment by Keksuccino** [comment]
Added in Linguji v1.1.1! :)

**Comment by Keksuccino** [comment]
Just a small info: The default Libre Translate URL does not support Slovak for some reason. You need to use another [mirror](https://github.com/LibreTranslate/LibreTranslate?tab=readme-ov-file#mirrors) if you plan to use Libre.
